### ISSUE TITLE
PF6 - dark theme toggle in docs not toggling

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/react-log-viewer#82] opened 2024-10-25 20:16 UTC
The dark theme toggle in the docs is not toggling the dark theme. Likely it's a problem with the tokens - the log viewer should be able to be in dark mode even if the rest of the UI is in light theme.

**Comment by evwilkin** [comment] 2024-11-21 05:05
I believe this is due to [this scoping change tying the dark theme to the :root element](https://github.com/patternfly/patternfly/commit/565ba3a86c1e02ef2a539817bc1fb61a4e523a84#diff-a45bf4133c6d676f39073b439f56d2ccc7ec8cb842ac137867dcd7c6765e1e6bR14) - I confirmed the dark toggle button works correctly with the alpha version before this PR was merged and no longer works with the version after this PR merged.
- The border around the example disappears when the dark theme is toggled because that rule is [coded directly to a dark var in the Log Viewer css](https://github.com/patternfly/react-log-viewer/blob/main/packages/module/src/LogViewer/css/log-viewer.css#L53-L55)

**Comment by evwilkin** [comment] 2024-11-21 14:15
@mcoker may be able to confirm above

**Comment by jdrews** [comment] 2024-12-01 22:02
I noticed that upgrading to 6.0.0 caused `theme={"dark"}` to stop working (not applying the dark theme to LogViewer component). I rolled back to 5.3.0 and dark mode started working again.

**Comment by mcoker** [comment] 2024-12-02 22:49
Recap of a working session convo w/ @dlabaj and @andrew-ronaldson 

* Change the log viewer's dark theme class from `.pf-v6-theme-dark` back to `.pf-m-dark`.
  * This isn't a required change since I believe the dark theme log viewer _should_ work w/ `.pf-v6-theme-dark`, but `.pf-v6-theme-dark` is currently used to convert all tokens to their dark theme equivalents, and this log viewer feature is more specific to a dark theme version of log viewer. So `.pf-m-dark` is more appropriate here IMO.
  * This will require an update to these places https://github.com/patternfly/react-log-viewer/blob/fdceccae5f434575dbdc48aa2b562525107695ac/packages/module/src/LogViewer/LogViewer.tsx#L315  https://github.com/patternfly/react-log-viewer/blob/fdceccae5f434575dbdc48aa2b562525107695ac/packages/module/src/LogViewer/css/log-viewer.css#L53 https://github.com/patternfly/react-log-viewer/blob/fdceccae5f434575dbdc48aa2b562525107695ac/packages/module/src/LogViewer/css/log-viewer.css#L56
* Use "inverse" tokens for the dark theme styles
  * Dark background color should use `--pf-t--global--background--color--inverse--default`
  * Light text color should use `--pf-t--global--text--color--inverse`
  * Remove the `main__BorderColor` and `--m-line-numbers` vars as they're not needed. The light theme border color works in the dark log viewer.

On the last bullet to use inverse colors, this is how I might try to update this block https://github.com/patternfly/react-log-viewer/blob/fdceccae5f434575dbdc48aa2b562525107695ac/packages/module/src/LogViewer/css/log-viewer.css#L53-L62

```
// Add these to the list of variables at the beginning
.pf-v6-c-log-viewer {
  --pf-v6-c-log-viewer--m-dark__main--BackgroundColor: var(--pf-t--global--background--color--inverse--default);
  --pf-v6-c-log-viewer--m-dark__text--Color: var(--pf-t--global--text--color--inverse);
  --pf-v6-c-log-viewer--m-dark__index--Color: var(--pf-t--global--text--color--inverse);
}

// This replaces the existing 2 `.pf-v6-theme-dark` style blocks referenced above
.pf-v6-c-log-viewer.pf-m-dark {
  --pf-v6-c-log-viewer__main--BorderWidth: var(--pf-v6-c-log-viewer--m-dark__main--BorderWidth);
  --pf-v6-c-log-viewer__main--BackgroundColor: var(--pf-v6-c-log-viewer--m-dark__main--BackgroundColor);
  --pf-v6-c-log-viewer__text--Color: var(--pf-v6-c-log-viewer--m-dark__text--Color);
  --pf-v6-c-log-viewer__index--Color: var(--pf-v6-c-log-viewer--m-dark__index--Color);
}
```

**Closed** 2024-12-04 20:42 UTC
Labels: release blocking
